### ISSUE TITLE
Sign out button will overlap

### ISSUE THREAD

**Issue by juliusl** [JoshuaKGoldberg/intern-assassins#141]
I made this happen, but I will fix this later.

<img width="759" alt="screen shot 2016-06-27 at 8 01 51 pm" src="https://cloud.githubusercontent.com/assets/5741075/16402580/159c4d30-3ca2-11e6-88cf-d106b11ce890.png">

**Comment by JoshuaKGoldberg** [comment]
Fixed in 4f99e3a118dd53528a33a30591265b1bba5f9662.
