### ISSUE TITLE
Stuck on "Loading..." in Safari

### ISSUE THREAD

**Issue by juliusl** [JoshuaKGoldberg/intern-assassins#93]
**Repro:** 

Build project on a Mac
Start the project
Navigate to localhost:3000 in Safari

**Expected:**
Login loads

**Actual:**
Stuck on "Loading..."

My best guess at the moment is that Safari has a weird WebSockets issue. Haven't dived too deep into it since it works fine in Chrome.

**Comment by JoshuaKGoldberg** [comment]
Some good things to see:
* Console errors
* Any other browsers this repros on

**Comment by JoshuaKGoldberg** [comment]
Probably a dup of https://github.com/JoshuaKGoldberg/intern-assassins/issues/111

**Comment by JoshuaKGoldberg** [comment]
I believe this was fixed in #125.
